const gridScoreVersion = '2.0.0'

const NAVIGATION_MODE_DRAG = 'DRAG'
const NAVIGATION_MODE_JUMP = 'JUMP'

const DISPLAY_ORDER_TOP_TO_BOTTOM = 'TOP_TO_BOTTOM'
const DISPLAY_ORDER_BOTTOM_TO_TOP = 'BOTTOM_TO_TOP'
const DISPLAY_ORDER_LEFT_TO_RIGHT = 'LEFT_TO_RIGHT'
const DISPLAY_ORDER_RIGHT_TO_LEFT = 'RIGHT_TO_LEFT'

const TRAIT_TIMEFRAME_TYPE_SUGGEST = 'SUGGEST'
const TRAIT_TIMEFRAME_TYPE_ENFORCE = 'ENFORCE'

export {
  gridScoreVersion,
  NAVIGATION_MODE_DRAG,
  NAVIGATION_MODE_JUMP,
  DISPLAY_ORDER_TOP_TO_BOTTOM,
  DISPLAY_ORDER_BOTTOM_TO_TOP,
  DISPLAY_ORDER_LEFT_TO_RIGHT,
  DISPLAY_ORDER_RIGHT_TO_LEFT,
  TRAIT_TIMEFRAME_TYPE_SUGGEST,
  TRAIT_TIMEFRAME_TYPE_ENFORCE
}
