const gridScoreVersion = '2.5.2'

const NAVIGATION_MODE_DRAG = 'DRAG'
const NAVIGATION_MODE_JUMP = 'JUMP'

const DISPLAY_ORDER_TOP_TO_BOTTOM = 'TOP_TO_BOTTOM'
const DISPLAY_ORDER_BOTTOM_TO_TOP = 'BOTTOM_TO_TOP'
const DISPLAY_ORDER_LEFT_TO_RIGHT = 'LEFT_TO_RIGHT'
const DISPLAY_ORDER_RIGHT_TO_LEFT = 'RIGHT_TO_LEFT'

const TRAIT_TIMEFRAME_TYPE_SUGGEST = 'SUGGEST'
const TRAIT_TIMEFRAME_TYPE_ENFORCE = 'ENFORCE'

const TRIAL_STATE_NOT_SHARED = 'NOT_SHARED'
const TRIAL_STATE_OWNER = 'OWNER'
const TRIAL_STATE_EDITOR = 'EDITOR'
const TRIAL_STATE_VIEWER = 'VIEWER'

const CANVAS_DENSITY_HIGH = 'high'
const CANVAS_DENSITY_MEDIUM = 'medium'
const CANVAS_DENSITY_LOW = 'low'

const CANVAS_SIZE_SMALL = 'small'
const CANVAS_SIZE_MEDIUM = 'medium'
const CANVAS_SIZE_LARGE = 'large'

const CANVAS_SHAPE_CIRCLE = 'circle'
const CANVAS_SHAPE_SQUARE = 'square'

const TRIAL_LIST_TABBED = 'tabbed'
const TRIAL_LIST_ALL = 'all'
const TRIAL_LIST_GRID = 'grid'
const TRIAL_LIST_LIST = 'list'

export {
  gridScoreVersion,
  NAVIGATION_MODE_DRAG,
  NAVIGATION_MODE_JUMP,
  DISPLAY_ORDER_TOP_TO_BOTTOM,
  DISPLAY_ORDER_BOTTOM_TO_TOP,
  DISPLAY_ORDER_LEFT_TO_RIGHT,
  DISPLAY_ORDER_RIGHT_TO_LEFT,
  TRAIT_TIMEFRAME_TYPE_SUGGEST,
  TRAIT_TIMEFRAME_TYPE_ENFORCE,
  TRIAL_STATE_NOT_SHARED,
  TRIAL_STATE_OWNER,
  TRIAL_STATE_EDITOR,
  TRIAL_STATE_VIEWER,
  CANVAS_DENSITY_HIGH,
  CANVAS_DENSITY_MEDIUM,
  CANVAS_DENSITY_LOW,
  CANVAS_SHAPE_CIRCLE,
  CANVAS_SHAPE_SQUARE,
  CANVAS_SIZE_SMALL,
  CANVAS_SIZE_MEDIUM,
  CANVAS_SIZE_LARGE,
  TRIAL_LIST_TABBED,
  TRIAL_LIST_ALL,
  TRIAL_LIST_GRID,
  TRIAL_LIST_LIST
}
