/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPersonModal: typeof import('./components/modals/AddPersonModal.vue')['default']
    AddTraitModal: typeof import('./components/modals/AddTraitModal.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ArrowDirectionGrid: typeof import('./components/util/ArrowDirectionGrid.vue')['default']
    ChangelogModal: typeof import('./components/modals/ChangelogModal.vue')['default']
    ColumnHeader: typeof import('./components/data/ColumnHeader.vue')['default']
    ConfirmModal: typeof import('./components/modals/ConfirmModal.vue')['default']
    copy: typeof import('./components/data/VScroll copy.vue')['default']
    CornerPointsMap: typeof import('./components/setup/CornerPointsMap.vue')['default']
    DataCanvas: typeof import('./components/data/DataCanvas.vue')['default']
    DataEntryModal: typeof import('./components/modals/DataEntryModal.vue')['default']
    DataGrid: typeof import('./components/data/DataGrid.vue')['default']
    FieldHubInputModal: typeof import('./components/modals/FieldHubInputModal.vue')['default']
    GenericAddEditFormModal: typeof import('./components/modals/GenericAddEditFormModal.vue')['default']
    GermplasmLayoutTable: typeof import('./components/setup/GermplasmLayoutTable.vue')['default']
    GpsInput: typeof import('./components/inputs/GpsInput.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HScroll: typeof import('./components/data/HScroll.vue')['default']
    JumpToDropdown: typeof import('./components/util/JumpToDropdown.vue')['default']
    LayoutMarkers: typeof import('./components/setup/LayoutMarkers.vue')['default']
    MapComponent: typeof import('./components/util/MapComponent.vue')['default']
    NumberInputWithFallback: typeof import('./components/inputs/NumberInputWithFallback.vue')['default']
    OffscreenCanvas: typeof import('./components/data/OffscreenCanvas.vue')['default']
    PlotCanvas: typeof import('./components/data/PlotCanvas.vue')['default']
    PlotDataInformation: typeof import('./components/plot/PlotDataInformation.vue')['default']
    PlotInformation: typeof import('./components/plot/PlotInformation.vue')['default']
    ResponsiveButton: typeof import('./components/util/ResponsiveButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowHeader: typeof import('./components/data/RowHeader.vue')['default']
    SearchResultModal: typeof import('./components/modals/SearchResultModal.vue')['default']
    StyledQRCode: typeof import('./components/util/StyledQRCode.vue')['default']
    TabbedInputModal: typeof import('./components/modals/TabbedInputModal.vue')['default']
    TraitDropdown: typeof import('./components/trial/TraitDropdown.vue')['default']
    TraitImportFromTrialModal: typeof import('./components/modals/TraitImportFromTrialModal.vue')['default']
    TraitInput: typeof import('./components/inputs/TraitInput.vue')['default']
    TraitInputSection: typeof import('./components/trait/TraitInputSection.vue')['default']
    TraitSection: typeof import('./components/trait/TraitSection.vue')['default']
    TrialCard: typeof import('./components/trial/TrialCard.vue')['default']
    TrialCreation: typeof import('./components/trial/TrialCreation.vue')['default']
    TrialDetails: typeof import('./components/setup/TrialDetails.vue')['default']
    TrialImport: typeof import('./components/trial/TrialImport.vue')['default']
    TrialLayout: typeof import('./components/setup/TrialLayout.vue')['default']
    TrialOptionsDropdown: typeof import('./components/trial/TrialOptionsDropdown.vue')['default']
    TrialSelector: typeof import('./components/trial/TrialSelector.vue')['default']
    TrialShareModal: typeof import('./components/modals/TrialShareModal.vue')['default']
    TrialSynchonizationModal: typeof import('./components/modals/TrialSynchonizationModal.vue')['default']
    TrialTraits: typeof import('./components/setup/TrialTraits.vue')['default']
    VScroll: typeof import('./components/data/VScroll.vue')['default']
  }
}
